
--THIS CONTAINS A DATASET MADE OF DETAILS OF AIR BNB LISTINGS AVAILABLE IN CERTAIN  NEIGHBOURHOODS IN NEW YORK CITY,
--AND SQL QUERIES AIMED AT EXPLORING THE CONTENTS OF THIS DATA.
--THE AIM OF THESE QUERIES IS TO GET INSIGHTS ON THE FEATURES OF THE AIR BNB LISTINGS  PROVIDED IN THIS DATASET


--THIS QUERY SELECTS ALL THE COLUMNS AND THE FIRST TEN ROWS OF THE NEW YORK CITY AIR BNB LISTINGS DATA SET,
--IN ORDER TO GIVE A GLIMPSE OF THE COLUMNS AND DATA TYPES AVAILABLE FOR THIS ANALYSIS 
SELECT TOP (10) [Id]
      ,[Name]
      ,[Host_Id]
      ,[Host_Name]
      ,[Neighbourhood_Group]
      ,[Neighbourhood]
      ,[Latitude]
      ,[Longitude]
      ,[Room_Type]
      ,[Price]
      ,[Minimum_Nights]
      ,[Number_of__Reviews]
      ,[Last_Review]
      ,[Reviews_Per_Month]
      ,[Calculated_Host_Listings_Count]
      ,[Availability_365]
  FROM [nyc].[dbo].[AB_NYC_2019$]


  --THIS QUERY WILL CHANGE THE LAST_REVIEW COLUMN FROM DATETIME TO DATE DATA TYPE
   ALTER TABLE  [nyc].[dbo].[AB_NYC_2019$]
  ALTER COLUMN [Last_Review] DATE


  --THIS WILL RETURN THE TOP 10 MOST EXPENSIVE NEIGHBOURHOODS IN THE NEW YORK AIR BNB COMMUNITY BASED ON THE HIGHEST AVERAGE PRICES OF THEIR  LISTINGS
  SELECT TOP 10 Neighbourhood, AVG(Price) AS AveragePrice
  FROM [nyc].[dbo].[AB_NYC_2019$]
  GROUP BY Neighbourhood
  ORDER BY AVG(Price) DESC
  
--THIS QUERY WILL RETURN THE TOTAL NUMBER OF LISTINGS PER HOST IN EACH NEIGHBOURHOOD 
 SELECT Neighbourhood,[Host_Name],COUNT(Host_Id) as ListingsCount
  FROM [nyc].[dbo].[AB_NYC_2019$]
  WHERE [Host_Name] IS NOT NULL
  GROUP BY Neighbourhood,[Host_Name]
  ORDER BY COUNT(Host_Id) 

--THIS QUERY WILL RETURN THE PRICE DISTRIBUTION BY NEIGHBOURHOOD BY DISPLAYING PRICES AND THE COUNT OF NEIGHBOURHOODS THAT CHARGE EACH PRICE
SELECT Price, COUNT(*)
  FROM [nyc].[dbo].[AB_NYC_2019$]
  GROUP BY Price
  ORDER BY Price desc

  --THIS QUERY WILL RETURN THE AVERAGE PRICE, MAXIMUM PRICE AND MINIMUM PRICE CHARGED IN EACH NEIRHBOURHOOD.
  --THIS CAN PROVIDE INSIGHT ON THE CHEAPEST, MOST EXPENSIVE  AND AVERAGE PRICES OF AIR BNB IN EACH NEIRHBOURHOOD
SELECT Neighbourhood,
AVG(Price) AS AvgPrice,
MAX(Price) AS Maxprice,
MIN(Price) AS MinPrice
  FROM [nyc].[dbo].[AB_NYC_2019$]
  GROUP BY Neighbourhood


--THIS WILL CREATE A MONTHS COLUMN IN THE DATASET EXTRACTED FROM THE LAST REVIEW DATES 
ALTER TABLE [nyc].[dbo].[AB_NYC_2019$]
ADD MONTHS VARCHAR(50);
UPDATE  [nyc].[dbo].[AB_NYC_2019$]
 SET MONTHS = DATENAME(MONTH, Last_review)

--THIS WILL ALTER THE TABLE TO CREATE A SEASONS COLUMN  WHERE EACH SEASON WILL BE FILLED IN 
ALTER TABLE [nyc].[dbo].[AB_NYC_2019$]
ADD SEASONS VARCHAR(50);

--THIS WILL UPDATE THE SEASONS COLUMN , SETTING THE SEASONS TO 'SPRING','SUMMER','AUTUMN' AND 'WINTER' DEPENDING ON THE MONTH OF THE REVIEW DATE.
UPDATE  [nyc].[dbo].[AB_NYC_2019$]
SET SEASONS = 
  CASE WHEN MONTHS IN ('March','April','May') THEN 'Spring'
 WHEN MONTHS IN ('June', 'July', 'August') THEN 'Summer'
 WHEN MONTHS IN ('September','October','November') THEN 'Autumn'
 ELSE 'Winter'
 END 

--IN ORDER TO DETECT SEASONAL TRENDS, THIS QUERY WILL RETRIEVE THE AVERAGE PRICE PER SEASON IN ORDER TO DETECT IF THERE IS A SPIKE OR DECREASE IN PRICE DEPENDING ON THE TIME OF THE YEAR
SELECT SEASONS,AVG(Price) AS AvgPricePerSeason
  FROM [nyc].[dbo].[AB_NYC_2019$]
  GROUP BY  SEASONS
  ORDER BY AVG(Price)

--THIS QUERY WILL COUNT THE NUMBER OF ROOM TYPES ORDERED AND GROUP THE RESULT BY THE ROOM TYPES AVAILABLE
SELECT Room_Type,COUNT(*)
  FROM [nyc].[dbo].[AB_NYC_2019$]
  GROUP BY Room_Type
  ORDER BY COUNT(*)

  --THIS QUERY EXAMINES THE MOST COMMON ROOM TYPE AVAILABLE IN THE ENTIRE NEIGHBOURHOODS
  SELECT TOP 1 Room_Type, COUNT(*) AS RoomTypeCount
  FROM [nyc].[dbo].[AB_NYC_2019$]
  GROUP BY Room_Type
  ORDER BY COUNT(*)DESC ;

  --THIS QUERY EXAMINES THE COUNT OF EACH ROOM TYPE AVAILABLE IN THE EACH NEIGHBOURHOOD_GROUP 
  SELECT Neighbourhood_Group,Room_Type, COUNT(*)
 FROM  [nyc].[dbo].[AB_NYC_2019$]
  GROUP BY Neighbourhood_Group,Room_Type
  ORDER BY COUNT(*)

  --THIS QUERY RETRIEVES THE NUMBER  OF LISTINGS PER HOST IN DESCENDING ORDER IN ORDER TO FIND OUT WHICH HOST HAS THE MOST AIR BNB'S
  SELECT Host_Id,Host_Name, COUNT(*) AS No_Of_Listings
  FROM [nyc].[dbo].[AB_NYC_2019$]
  GROUP BY Host_Id, Host_Name
  ORDER BY COUNT(*) DESC

  --THIS WILL RETRIEVE AVERAGE PRICE PER HOST TO KNOW WHICH HOST CHARGES THE MOST MONEY FOR THEIR LISTING
  SELECT Host_Id,Host_Name,AVG(Price) AS AveragePricePerHost
  FROM [nyc].[dbo].[AB_NYC_2019$]
  GROUP BY Host_Id, Host_Name
  ORDER BY AVG(Price) DESC
 
 --THIS QUERY SELECTS THE MAXIMUM PRICE FOR EACH ROOM TYPE
 SELECT Room_Type ,MAX(Price) 
 FROM [nyc].[dbo].[AB_NYC_2019$]
  GROUP BY Room_Type

  --THIS QUERY RETURN THE MAXIMUM PRICE OF EACH LISTING PER YEAR
  SELECT YEAR(Last_Review) AS Year, MAX(Price) AS Maximum_Price
 FROM [nyc].[dbo].[AB_NYC_2019$]
 GROUP BY YEAR( Last_Review) 
 ORDER BY YEAR(Last_Review)

 --THIS QUERY RETURNS THE MAXIMUM PRICE OF LISTINGS IN EACH NEIGHBOURHOOD GROUP
  SELECT Neighbourhood_Group, MAX(Price) AS Maximum_Price
 FROM [nyc].[dbo].[AB_NYC_2019$]
 GROUP BY Neighbourhood_Group

 --THIS QUERY RETURNS THE NUMBER OF LISTINGS IN EACH NEIGHBOURHOOD GROUP
  SELECT Neighbourhood_Group,COUNT(*) AS Listings_Count
 FROM [nyc].[dbo].[AB_NYC_2019$]
 GROUP BY Neighbourhood_Group
 ORDER BY COUNT(*) DESC






